name = "PClean"
uuid = "ad4d8a49-b7a6-42f4-9958-4de6b66581ba"
authors = ["alex-lew <alexl.mail@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"

[compat]
CSV = "0.10.14"
DataFrames = "1.6.1"
julia = "1.10"
Distributions = "0.25.109"
LightGraphs = "1.3.5"
MacroTools = "0.5.13"
StringDistances = "0.11.3"
